# Generated by Django 5.0.6 on 2024-07-06 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('imagen', models.ImageField(upload_to='imagenes/')),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('detalle', models.TextField()),
                ('stock', models.IntegerField()),
                ('codigo', models.CharField(max_length=255)),
                ('envio', models.BooleanField(default=True)),
                ('retiro', models.BooleanField(default=True)),
                ('categoria', models.CharField(choices=[('alimentos', 'Alimentos'), ('exoticos', 'Exóticos'), ('farmacia', 'Farmacia'), ('juguetes', 'Juguetes'), ('limpieza', 'Limpieza'), ('ropa', 'Ropa')], max_length=20)),
            ],
        ),
    ]
